name: QIT Self-Tests
on:
  # Every day at 9pm UTC
  schedule:
    - cron: '0 21 * * *'
  # Manually
  workflow_dispatch:
  # On push to trunk
  push:
    branches:
      - trunk
jobs:
  qit_self_tests:
    name: QIT Self Tests - ${{ matrix.test_type }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        test_type: ["activation", "api", "e2e", "phpstan", "security"]
    env:
      NO_COLOR: 1
      QIT_DISABLE_ONBOARDING: yes
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'

      - name: Composer install
        working-directory: _tests
        run: composer install

      - name: Connect to QIT
        run: ./qit partner:add --user=${{ secrets.QIT_USER }} --application_password=${{ secrets.QIT_ACCESS_TOKEN }}

      - name: Run Self-Tests
        id: run-self-tests
        if: (github.event_name != 'push' || matrix.test_type != 'e2e') # Do not run e2e tests on push, since they take long.
        working-directory: _tests
        env:
          QIT_WAIT_BEFORE_REQUEST: yes
        run: php ./QITSelfTests.php run ${{ matrix.test_type }}
