name: QIT E2E - Security Test
on:
  workflow_dispatch:
  push:
    branches:
      - trunk
jobs:
  qit_security:
    name: QIT Security
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'
      - name: Composer install
        working-directory: _tests
        run: composer install
      - name: Enable QIT development mode
        run: ./qit dev
      - name: Connect to QIT Staging
        run: ./qit env:add --environment=staging --manager_url=https://stagingcompatibilitydashboard.wpcomstaging.com --qit_secret=${{ secrets.QIT_STAGING_SECRET }}
      - name: Create Zip.
        working-directory: _tests/security
        run: docker run --rm --user $(id -u):$(id -g) -v "$GITHUB_WORKSPACE:/app" -w /app joshkeegan/zip:latest sh -c "zip -r automatewoo.zip automatewoo"
      - name: Run Security Test.
        id: run-security-test
        run: ./qit run:security automatewoo --zip=_tests/security/automatewoo.zip --wait > _tests/security.txt
      - name: Check Results
        id: check-security-test
        working-directory: _tests
        run: php ./vendor/bin/phpunit tests/SecurityTest.php
