name: QIT Self-Tests

on:
  # Every day at 9pm UTC
  schedule:
    - cron: '0 21 * * *'
  # Manually
  workflow_dispatch:
  # On push to trunk
  push:
    branches:
      - trunk

jobs:
  api_tests:
    uses: ./.github/workflows/self-test-template.yml
    with:
      test_type: api
    secrets:
      QIT_USER: ${{ secrets.QIT_USER }}
      QIT_ACCESS_TOKEN: ${{ secrets.QIT_ACCESS_TOKEN }}

  security_tests:
    uses: ./.github/workflows/self-test-template.yml
    with:
      test_type: security
    secrets:
      QIT_USER: ${{ secrets.QIT_USER }}
      QIT_ACCESS_TOKEN: ${{ secrets.QIT_ACCESS_TOKEN }}

  e2e_tests:
    if: github.event_name != 'push'
    uses: ./.github/workflows/self-test-template.yml
    with:
      test_type: e2e
    secrets:
      QIT_USER: ${{ secrets.QIT_USER }}
      QIT_ACCESS_TOKEN: ${{ secrets.QIT_ACCESS_TOKEN }}

  phpstan_tests:
    uses: ./.github/workflows/self-test-template.yml
    with:
      test_type: phpstan
    secrets:
      QIT_USER: ${{ secrets.QIT_USER }}
      QIT_ACCESS_TOKEN: ${{ secrets.QIT_ACCESS_TOKEN }}

  activation_tests:
    uses: ./.github/workflows/self-test-template.yml
    with:
      test_type: activation
    secrets:
      QIT_USER: ${{ secrets.QIT_USER }}
      QIT_ACCESS_TOKEN: ${{ secrets.QIT_ACCESS_TOKEN }}
