name: QIT Self-Test - Security Test
on:
  # Every day at 9pm UTC
  schedule:
    - cron: '0 21 * * *'
  # Manually
  workflow_dispatch:
  # On push to trunk
  push:
    branches:
      - trunk
jobs:
  qit_security_prepare:
    name: QIT Security
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'
      - name: Composer install
        working-directory: _tests
        run: composer install

      - name: Enable QIT development mode
        run: ./qit dev

      - name: Connect to QIT Staging
        run: ./qit env:add --environment=staging --manager_url=https://stagingcompatibilitydashboard.wpcomstaging.com --qit_secret=${{ secrets.QIT_STAGING_SECRET }}

      - uses: actions/cache@v3
        id: cache-composer
        with:
          path: $(./qit qit:dir)
          key: qit-config

  qit_security_test_main:
    name: QIT Security - Main
    runs-on: ubuntu-20.04
    needs: [qit_security_prepare]
    steps:
      - uses: actions/cache@v3
        id: cache-composer
        with:
          path: $(./qit qit:dir)
          key: qit-config

      - name: Create Zip.
        working-directory: _tests/security/main
        run: docker run --rm --user $(id -u):$(id -g) -v "$(pwd):/app" -w /app joshkeegan/zip:latest sh -c "zip -r woocommerce-product-feeds.zip woocommerce-product-feeds"

      - name: Run Security Test.
        id: run-security-test
        run: ./qit run:security woocommerce-product-feeds --zip=_tests/security/main/woocommerce-product-feeds.zip --wait --ignore-fail --timeout=300 --json > _tests/security-main.txt

      - name: Check Results
        id: check-security-test
        working-directory: _tests
        run: php ./vendor/bin/phpunit tests/SecurityTest.php
