name: QIT Self-Test - Activation Test
on:
  # Every day at 9pm UTC
  schedule:
    - cron: '0 21 * * *'
  # Manually
  workflow_dispatch:
  # On push to trunk
  push:
    branches:
      - trunk
jobs:
  qit_activation_prepare:
    name: QIT Activation
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'

      - name: Composer install
        working-directory: _tests
        run: composer install

      - name: Enable QIT development mode
        run: ./qit dev

      - name: Connect to QIT Staging
        run: ./qit env:add --environment=staging --manager_url=https://stagingcompatibilitydashboard.wpcomstaging.com --qit_secret=${{ secrets.QIT_STAGING_SECRET }}

      - uses: actions/cache@v3
        id: cache-composer
        with:
          path: $(./qit qit:dir)
          key: qit-config

  qit_activation_test_main:
    name: QIT Activation - Main
    runs-on: ubuntu-20.04
    needs: [qit_activation_prepare]
    steps:
      - uses: actions/cache@v3
        id: cache-composer
        with:
          path: $(./qit qit:dir)
          key: qit-config

      - name: Create Zip.
        working-directory: _tests/activation/main
        run: docker run --rm --user $(id -u):$(id -g) -v "$(pwd):/app" -w /app joshkeegan/zip:latest sh -c "zip -r woocommerce-product-feeds.zip woocommerce-product-feeds"

      - name: Run Activation Test.
        id: run-activation-test
        run: ./qit run:activation woocommerce-product-feeds --zip=_tests/activation/main/woocommerce-product-feeds.zip --wait --ignore-fail --timeout=420 --json > _tests/activation-main.txt

      - name: Check Results
        id: check-activation-test
        working-directory: _tests
        run: php ./vendor/bin/phpunit tests/ActivationTest.php --filter=test_main_activation

  qit_activation_test_php82:
    name: QIT Activation - PHP 8.2
    runs-on: ubuntu-20.04
    needs: [qit_activation_prepare]
    steps:
      - uses: actions/cache@v3
        id: cache-composer
        with:
          path: $(./qit qit:dir)
          key: qit-config

      - name: Create Zip.
        working-directory: _tests/activation/php82
        run: docker run --rm --user $(id -u):$(id -g) -v "$(pwd):/app" -w /app joshkeegan/zip:latest sh -c "zip -r woocommerce-product-feeds.zip woocommerce-product-feeds"

      - name: Run Activation Test.
        id: run-activation-test
        run: ./qit run:activation woocommerce-product-feeds --zip=_tests/activation/php82/woocommerce-product-feeds.zip --wait --ignore-fail --timeout=420 --json > _tests/activation-php82.txt

      - name: Check Results
        id: check-activation-test
        working-directory: _tests
        run: php ./vendor/bin/phpunit tests/ActivationTest.php --filter=test_php82_activation
